config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
      }
  get 'home/index'	
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  #PROFILES
  get 'profile', to: 'profiles#index'
  get 'viewProfiles', to: 'profiles#viewProfiles'

  #INVOICES
  get 'upload', to: 'invoices#index', as: :upload_file
  post 'upload', to: 'invoices#upload'
  get 'viewInvoices', to: 'invoices#viewInvoices'
  get 'saveReceipt', to: 'invoices#viewInvoices'
  post 'saveReceipt', to: 'invoices#saveReceipt'
  get 'destroyReceipt', to: 'invoices#viewInvoices'
  post 'destroyReceipt', to: 'invoices#destroyReceipt'
  get 'viewDetail', to: 'invoices#viewDetail'

 #authentication
  



end

app/controllers/invoices_controller.rb
require 'date'

class InvoicesController < ApplicationController
	$x = nil
	$tipodefactura = nil;
	def viewInvoices
		if (current_user.admin)
			@receipt = Receipt.where("user_email = ?", params[:email])
		else
			@receipt = Receipt.where("user_email = ?", current_user.email)
		end
	end
	def index
		if !$x.nil?
			xml_file = File.read("app/importers/uploads/" + $x)
			doc = Nokogiri::XML.parse(xml_file)
			@root = doc.root
			receptor = doc.xpath('//cfdi:Receptor')
			emisor = doc.xpath('//cfdi:Emisor')
			total = doc.xpath('//cfdi:Comprobante')
			impuestos = doc.xpath('//cfdi:Traslado')
			@nombreEmisor = emisor[0]["nombre"]
			@rfcEmisor = emisor[0]["rfc"]
			@nombreReceptor = receptor[0]["nombre"]
			@rfcReceptor = receptor[0]["rfc"]
			@subtotal = total[0]["subTotal"]
			@iva = impuestos[0]["importe"]
			@pagoTotal = total[0]["total"]
			@tipodeFactura = $tipodefactura
		end
		# Parse the URI and retrieve it to a temporary file
	end
		#html output
		#html =  "Emisor: " + nombreEmisor + " RFC Emisor : " + rfcEmisor + "\n" +
		#		"Receptor: " + nombreReceptor + " RFC Receptor : " + rfcReceptor + "\n" +
		#		"Subtotal: " + subtotal + " IVA: " + iva + " Total: " + pagoTotal

		#extract the title from the articles
	def saveReceipt
		current_time = DateTime.now
		Receipt.create!(:concept => params[:tipofactura],
							:subtotal => params[:subtotal],
							:total => params[:pagototal],
							:iva => params[:iva],
							:xml => params[:rawxml],
							:users_id => current_user.id,
							:created_at => current_time,
							:updated_at => current_time,
							:user_email => current_user.email,
							:emisor => params[:emisor],
							:rfcEmisor => params[:rfcemisor],
							:receptor => params[:receptor],
							:rfcReceptor => params[:rfcreceptor])
		redirect_to action: 'viewInvoices' , email: current_user.email
	end

	def upload
		if !params[:receipt].nil?
			uploaded_io = params[:receipt][:factura]
			File.open(Rails.root.join('app/importers', 'uploads', uploaded_io.original_filename), 'wb') do |file|
			  file.write(uploaded_io.read)
			end
			$x = uploaded_io.original_filename
			$tipodefactura = params[:tipofactura]
			redirect_to action: 'index'
		end
	end
	
	def destroyReceipt
		@email = Receipt.where("id = ?", params[:id]).map(&:user_email)
		Receipt.find(params[:id]).destroy
		redirect_to action: 'viewInvoices' , email: @email[0]
	end


	def viewDetail
		@concepto = Receipt.where("id = ?", params[:id]).map(&:concept)
		@id = params[:id]
		@root = Receipt.where("id = ?", params[:id]).map(&:xml)
		@date = Receipt.where("id = ?", params[:id]).map(&:created_at)
		@emisor = Receipt.where("id = ?", params[:id]).map(&:emisor)
		@rfcEmisor = Receipt.where("id = ?", params[:id]).map(&:rfcEmisor)
		@receptor = Receipt.where("id = ?", params[:id]).map(&:receptor)
		@rfcReceptor = Receipt.where("id = ?", params[:id]).map(&:rfcReceptor)
		@subtotal = Receipt.where("id = ?", params[:id]).map(&:subtotal)
		@iva = Receipt.where("id = ?", params[:id]).map(&:iva)
		@total = Receipt.where("id = ?", params[:id]).map(&:total)
	end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/index.html.erb
  <br><br><br>
  <div class="container">
  <div class="flex-v-center">
    <div class="form-group">
      <label for="exampleInputFile" style="padding-bottom:15px">Ingresa el archivo</label>
       <%= form_for Receipt.new, url: upload_file_path do |f| %>
        <%= f.file_field :factura, accept: 'text/xml'%>
        <br>
        <p> <%= radio_button_tag :tipofactura,  "Emitida" %> Emitida</p>
        <p> <%= radio_button_tag :tipofactura, "Recibida" %> Recibida</p>
        <br>
        <%= submit_tag " Subir XML Y Tipo "%>
      <% end %>
    </div>
    
    <div class="form-group">
        <label for="exampleInputFile">Tipo de Factura</label>
          <p> <%= @tipodeFactura %> </p>
    </div>

  </div>

<div class="row">
  <div id="table">
      <table class="table">
        <thead>
          <th class="col-md-1">Datos</th>
          <th class="col-md-1"></th>
        </thead>
        <tbody>
        <tr><strong> Vista Previa: </strong></tr>
        <tr>
            <textarea class="form-control" placeholer="Message"rows="10" disabled>
              <%= @root %>
            </textarea>
        </tr>
        <tr>
          <td><strong>Emisor:</strong></td>
          <td><%= @nombreEmisor %></td>
        </tr>
        <tr>
          <td><strong>RFC del Emisor:</strong></td>
          <td><%= @rfcEmisor %></td>
        </tr>
        <tr>
          <td><strong>Receptor:</strong></td>
          <td><%= @nombreReceptor %></td>
        </tr>
        <tr>
          <td><strong>RFC del Receptor:</strong></td>
          <td><%= @rfcReceptor %></td>
        </tr>
        <tr>
          <td><strong>subTotal:</strong></td>
          <td><%= @subtotal %></td>
        </tr>
        <tr>
          <td><strong>IVA:</strong></td>
          <td><%= @iva %></td>
        </tr>
        <tr>
          <td><strong>Total:</strong></td>
          <td><%= @pagoTotal %></td>
        </tr>
      </tbody>
      </table>
  </div>
</div>

    <%= button_to "Guardar Factura", saveReceipt_path(:rawxml => @root, :emisor => @nombreEmisor, :rfcemisor => @rfcEmisor, :receptor => @nombreReceptor, :rfcreceptor => @rfcReceptor, :subtotal => @subtotal, :iva => @iva, :pagototal => @pagoTotal, :tipofactura => @tipodeFactura), :class => "btn btn-primary" %>
</div>
</br> </br>

app/views/invoices/viewDetail.html.erb
  <br><br><br>
  <div class="container">
  <form>

<div class="row">
  <div id="table">
      <table class="table">
        <thead>
          <th class="col-md-1">Datos</th>
          <th class="col-md-1"></th>
        </thead>
        <tbody>
        <tr><strong> Vista Previa: </strong></tr>
        <tr>
            <textarea class="form-control" placeholer="Message"rows="10" disabled>
              <%= @root %>
            </textarea>

        </tr>
        <tr>
          <td><strong>ID:</strong></td>
          <td><%= @id%></td>
        </tr>
        <tr>
          <td><strong>Concepto:</strong></td>
          <td><%= @concepto[0]%></td>
        </tr>
        <tr>
          <td><strong>Añadida en:</strong></td>
          <td><%= Date.parse(@date.to_s()).strftime("%e / %m / %Y") %></td>
        </tr>
        <tr>
          <td><strong>Emisor:</strong></td>
          <td><%= @emisor[0]%></td>
        </tr>
        <tr>
          <td><strong>RFC del Emisor:</strong></td>
          <td><%= @rfcReceptor[0]%></td>
        </tr>
        <tr>
          <td><strong>Receptor:</strong></td>
          <td><%= @receptor[0]%></td>
        </tr>
        <tr>
          <td><strong>RFC del Receptor:</strong></td>
          <td><%= @rfcReceptor[0] %></td>
        </tr>
        <tr>
          <td><strong>subTotal:</strong></td>
          <td><%= @subtotal[0] %></td>
        </tr>
        <tr>
          <td><strong>IVA:</strong></td>
          <td><%= @iva[0] %></td>
        </tr>
        <tr>
          <td><strong>Total:</strong></td>
          <td><%= @total[0] %></td>
        </tr>
      </tbody>
      </table>
  </div>
  
</div>



</form>
</div>
<div align = "center">

 <%= button_to "Borrar Factura", destroyReceipt_path(id: @id), :class => "btn btn-secondary" %>
</div>

app/views/invoices/viewInvoices.html.erb
<br><br><br>
<div class="container">
<form>

 <!--  <strong style="padding-bottom:15px;"> Elige el tipo de factura que quieres al llenar los siguientes campos: </strong> -->
 <!--
  <div class="flex-v-center center-text">
      <div class="form-group">
        <label for="exampleInputFile">Tipo de Factura</label>
          <select class="form-control" id = "tipo" onchange="getval(this);" >
            <option>Ninguno</option>
            <option>Emitido</option>
            <option>Recibido</option>
          </select>
      </div>
    
      <div class="form-group" style="padding-left:20px">
        <label for="exampleInputFile">Mes</label>
          <select class="form-control">
            <option>Enero</option>
            <option>Febrero</option>
            <option>Marzo</option>
            <option>Abril</option>
            <option>Mayo</option>
            <option>Junio</option>
            <option>Julio</option>
            <option>Agosto</option>
            <option>Septiembre</option>
            <option>Octubre</option>
            <option>Noviembre</option>
            <option>Diciembre</option>
          </select>
      </div>

      <div class="form-group" style="padding-left:20px">
          <label for="exampleInputFile">Año</label>
          <select class="form-control">
            <option>1</option>
            <option>2</option>
            <option>3</option>
            <option>4</option>
            <option>5</option>
            <option>6</option>
            <option>7</option>
            <option>8</option>
            <option>9</option>
            <option>10</option>
            <option>11</option>
            <option>12</option>
          </select>
      </div>
      <div class="form-group" style="padding-left:20px; padding-top:30px">
        <%= link_to 'Actualizar', {:controller => "invoices", :action => "viewInvoices", :tipo =>  'E'}%>
      </div>
  </div>
</form>
-->
 <div id="table-div">
    <table class="table">
      <thead>
        <div class="row">
        <th class="col-md-2">Clave de Factura</th>
        <th class="col-md-1">Mes</th>
        <th class="col-md-1">Año</th>
        <th class="col-md-2">Emisor</th>
        <th class="col-md-2">Receptor</th>
        <th class="col-md-2">Concepto</th>
        <th class="col-md-1">Total</th>
        </div>
      </thead>
      <tbody>
        <% @receipt.each do |r| %>
            <tr>
                <td><%= link_to r.id, viewDetail_path(id: r.id)%></td>
                <td><%= r.created_at.month%> </td>
                <td><%= r.created_at.year%> </td>
                <td><%= r.user_email %> </td>
                <td><%= r.user_email %> </td>
                <td><%= r.concept %> </td>
                <td><%= r.total %> </td>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>

      <!-- Modal -->
      <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">Datos de Facturación</h4>
            </div>
            <div class="modal-body">
                  <form class="form-horizontal" role="form" method="post" action="#">
                      <div class="form-group">
                          <label for="tema" class="col-sm-2 control-label">Tema</label>
                          <div class="col-sm-10">
                            <input type="text" class="form-control" id="tema" name="tema" placeholder="Tema" value="">
                          </div>
                      </div>
                      <div class="form-group">
                          <label for="email" class="col-sm-2 control-label">Email</label>
                          <div class="col-sm-10">
                            <input type="email" class="form-control" id="email" name="email" placeholder="example@domain.com" value="">
                          </div>
                      </div>
                      <div class="form-group">
                          <label for="message" class="col-sm-2 control-label">Message</label>
                          <div class="col-sm-10">
                            <textarea class="form-control" rows="4" name="message"></textarea>
                          </div>
                        </div>
                      <div class="form-group">
                          <div class="col-sm-10 col-sm-offset-2">
                            <input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
                          </div>
                      </div>
                      <div class="form-group">
                          <div class="col-sm-10 col-sm-offset-2">
                            <!-- Will be used to display an alert to the user-->
                          </div>
                      </div>
                </form>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
          </div>

        </div>
      </div>
</div>